""" # noqa Y021
This type stub file was generated by pyright.
"""

from Xlib.protocol.request import AllocColor, AllocColorCells, AllocColorPlanes, AllocNamedColor, LookupColor
from Xlib.xobject import resource

rgb_res = ...


class Colormap(resource.Resource):
    __colormap__ = ...

    def free(self, onerror=...) -> None:
        ...

    def copy_colormap_and_free(self, scr_cmap):
        ...

    def install_colormap(self, onerror=...) -> None:
        ...

    def uninstall_colormap(self, onerror=...) -> None:
        ...

    def alloc_color(self, red, green, blue) -> AllocColor:
        ...

    def alloc_named_color(self, name) -> AllocColor | AllocNamedColor | None:
        ...

    def alloc_color_cells(self, contiguous, colors, planes) -> AllocColorCells:
        ...

    def alloc_color_planes(self, contiguous, colors, red, green, blue) -> AllocColorPlanes:
        ...

    def free_colors(self, pixels, plane_mask, onerror=...) -> None:
        ...

    def store_colors(self, items, onerror=...) -> None:
        ...

    def store_named_color(self, name, pixel, flags, onerror=...) -> None:
        ...

    def query_colors(self, pixels):
        ...

    def lookup_color(self, name) -> LookupColor:
        ...
