""" # noqa Y021
This type stub file was generated by pyright.
"""

from Xlib.xobject import resource

#


class Cursor(resource.Resource):
    __cursor__ = ...

    def free(self, onerror=...) -> None:
        ...

    def recolor(self, f_rgb, b_rgb, onerror=...) -> None:
        ...
