""" # noqa Y021
This type stub file was generated by pyright.
"""

from Xlib.protocol.request import QueryFont, QueryTextExtents
from Xlib.xobject import resource

#


class Fontable(resource.Resource):
    __fontable__ = ...

    def query(self) -> QueryFont:
        ...

    def query_text_extents(self, string) -> QueryTextExtents:
        ...


class GC(Fontable):
    __gc__ = ...

    def change(self, onerror=..., **keys) -> None:
        ...

    def copy(self, src_gc, mask, onerror=...) -> None:
        ...

    def set_dashes(self, offset, dashes, onerror=...) -> None:
        ...

    def set_clip_rectangles(self, x_origin, y_origin, rectangles, ordering, onerror=...) -> None:
        ...

    def free(self, onerror=...) -> None:
        ...


class Font(Fontable):
    __font__ = ...

    def close(self, onerror=...) -> None:
        ...

    def create_glyph_cursor(self, mask, source_char, mask_char, f_rgb, b_rgb):
        ...
