""" # noqa Y021
This type stub file was generated by pyright.
"""


class Resource:
    id: int = ...

    def __init__(self, display, rid, owner=...) -> None:
        ...

    def __resource__(self):
        ...

    def kill_client(self, onerror=...) -> None:
        ...
