""" # noqa Y021
This type stub file was generated by pyright.

Python mapping for the AppKit framework.

This module does not contain docstrings for the wrapped code, check Apple's
documentation for details on how to use these functions and classes.
"""

from typing import Any, TypeVar

import AppKit.NSScreen as NSSCreen

__all__ = ["NSScreen"]

Unknown = Any
_T = TypeVar("_T")


def NSDictionaryOfVariableBindings(names: list[_T]) -> dict[_T, Any]:
    ...
