""" # noqa Y021
This type stub file was generated by pyright.
"""

from . import XK, X, Xatom, Xcursorfont, Xutil, display, error, rdb

__version__ = ...
__version_extra__ = ...
__version_string__ = ...
__all__ = ['X', 'XK', 'Xatom', 'Xcursorfont', 'Xutil', 'display', 'error', 'rdb']
