""" # noqa Y021
This type stub file was generated by pyright.
"""

from typing import Literal

from Xlib.protocol import rq

#


class DisplayError(Exception):
    def __init__(self, display) -> None:
        ...


class DisplayNameError(DisplayError):
    ...


class DisplayConnectionError(DisplayError):
    def __init__(self, display, msg) -> None:
        ...


class ConnectionClosedError(Exception):
    def __init__(self, whom) -> None:
        ...


class XauthError(Exception):
    ...


class XNoAuthError(Exception):
    ...


class ResourceIDError(Exception):
    ...


class XError(rq.GetAttrData, Exception):
    _fields = ...

    def __init__(self, display, data) -> None:
        ...


class XResourceError(XError):
    _fields = ...


class BadRequest(XError):
    ...


class BadValue(XError):
    ...


class BadWindow(XResourceError):
    ...


class BadPixmap(XResourceError):
    ...


class BadAtom(XError):
    ...


class BadCursor(XResourceError):
    ...


class BadFont(XResourceError):
    ...


class BadMatch(XError):
    ...


class BadDrawable(XResourceError):
    ...


class BadAccess(XError):
    ...


class BadAlloc(XError):
    ...


class BadColor(XResourceError):
    ...


class BadGC(XResourceError):
    ...


class BadIDChoice(XResourceError):
    ...


class BadName(XError):
    ...


class BadLength(XError):
    ...


class BadImplementation(XError):
    ...


xerror_class = ...


class CatchError:
    def __init__(self, *errors) -> None:
        ...

    def __call__(self, error, request) -> Literal[1, 0]:
        ...

    def get_error(self) -> None:
        ...

    def get_request(self) -> None:
        ...

    def reset(self) -> None:
        ...
