""" # noqa Y021
This type stub file was generated by pyright.
"""

from typing import Any

#


def string_to_keysym(keysym) -> Any | int:
    ...


def load_keysym_group(group) -> None:
    ...


def keysym_to_string(keysym) -> str | None:
    ...
